"use client";

import { ArrowRight, Check, ChevronDown, Cloud, Sparkles } from "lucide-react";
import styles from "./onboarding.module.css";

export function PrimaryButton({ children, onClick, type = "button" }: { children: React.ReactNode; onClick?: () => void; type?: "button" | "submit" }) { return <button className={styles.primaryButton} type={type} onClick={onClick}>{children}<ArrowRight size={16}/></button>; }
export function FormInput({ label, placeholder, type = "text" }: { label: string; placeholder: string; type?: string }) { return <label className={styles.fieldLabel}>{label}<input className={styles.input} type={type} placeholder={placeholder}/></label>; }
export function Dropdown({ label, options, placeholder }: { label: string; options: string[]; placeholder: string }) { return <label className={styles.fieldLabel}>{label}<span className={styles.selectWrap}><select className={styles.input} defaultValue=""><option value="" disabled>{placeholder}</option>{options.map(option => <option key={option}>{option}</option>)}</select><ChevronDown size={15}/></span></label>; }
export function Stepper({ step }: { step: number }) { return <div className={styles.stepper}>{["Organization", "Goals", "Products", "Connect"].map((label, index) => <div className={styles.step} key={label}><span className={step > index + 1 ? styles.complete : step === index + 1 ? styles.current : ""}>{step > index + 1 ? <Check size={14}/> : index + 1}</span><b>{label}</b>{index < 3 && <i className={step > index + 1 ? styles.completeLine : ""}/>}</div>)}</div>; }
export function IntegrationCard({ name, connected, onConnect }: { name: string; connected: boolean; onConnect: () => void }) { return <article className={styles.integration}><span className={styles.integrationIcon}><Cloud size={17}/></span><div><b>{name}</b><small>{connected ? "Connected" : "Not connected"}</small></div><button className={connected ? styles.connected : styles.connect} onClick={onConnect}>{connected ? <Check size={14}/> : "Connect"}</button></article>; }
export function ProductCard({ index, onRemove }: { index: number; onRemove?: () => void }) { return <article className={styles.productCard}><div className={styles.productHeading}><span><Sparkles size={16}/></span><b>Product {index}</b>{onRemove && <button onClick={onRemove}>Remove</button>}</div><div className={styles.gridTwo}><FormInput label="Product name" placeholder="e.g. AI Infrastructure Platform"/><FormInput label="Category" placeholder="e.g. Cloud & AI"/><FormInput label="Short description" placeholder="What does this product do?"/><FormInput label="Target audience" placeholder="e.g. Enterprise IT teams"/><FormInput label="Pain points solved" placeholder="Cost, speed, security..."/><FormInput label="Competitors" placeholder="e.g. AWS, Google Cloud"/><Dropdown label="Pricing model" placeholder="Select a model" options={["Subscription", "Usage-based", "One-time", "Custom enterprise"]}/><FormInput label="Product URL" placeholder="https://yourproduct.com"/></div></article>; }
