import { ArrowUpRight, Bot, CalendarDays, ChevronRight, CircleDollarSign, Lightbulb, Plus, TrendingUp, UsersRound, Zap } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";

const metrics = [
  ["High intent accounts", "24", "+12.5% this month", Zap, "teal"], ["Revenue pipeline", "$4.82M", "+8.2% this quarter", CircleDollarSign, ""], ["Pipeline growth", "18.6%", "+4.1% vs last quarter", TrendingUp, "purple"], ["Average intent", "74", "+6 points this month", UsersRound, "orange"], ["Meetings today", "8", "2 need preparation", CalendarDays, "green"]
] as const;
const accounts = [["Novartis", "Healthcare", "$620K", "Proposal", "92"], ["Airtel Business", "Telecom", "$480K", "Discovery", "87"], ["Lumen Technologies", "Technology", "$350K", "Negotiation", "81"]];

function MetricCards() { return <section className="metrics">{metrics.map(([label,value,trend,Icon,tone]) => <article className="card" key={label}><div className="metric-label">{label}<span className={`metric-icon ${tone}`}><Icon size={15}/></span></div><div className="metric-number">{value}</div><div className="trend"><ArrowUpRight size={11}/> {trend}</div></article>)}</section>; }
function RevenueChart(){ const bars=[42,57,50,68,61,77,70,91,84,100,92,105]; return <article className="card"><div className="chart-head"><div><h2 className="card-title">Revenue pipeline</h2><p className="card-subtitle">Qualified pipeline by month</p></div><div className="period">Last 12 months</div></div><div className="chart-area"><div className="chart-bars">{bars.map((height,index)=><div className="bar-group" key={index}><div className="bar" style={{height:`${height - 18}%`}}/><div className="bar strong" style={{height:`${height}%`}}/></div>)}</div><div className="chart-labels"><span>Sep</span><span>Nov</span><span>Jan</span><span>Mar</span><span>May</span><span>Jul</span></div></div><div style={{display:"flex",gap:18,marginTop:15,fontSize:11,color:"#64748b"}}><span><b style={{color:"#2563eb"}}>●</b> Current pipeline</span><span><b style={{color:"#b9d0ff"}}>●</b> Previous period</span></div></article> }
function Suggestions(){return <article className="card"><div className="chart-head"><div><h2 className="card-title">AI recommendations</h2><p className="card-subtitle">Prioritized for today</p></div><Bot size={17} color="#7c3aed"/></div>{[["Prepare Novartis executive brief","High confidence", "Their new AI lab signals a $620K expansion opportunity."],["Engage Airtel's cloud leadership","Best next action", "Three new signals indicate an active modernization initiative."],["Follow up with Lumen procurement","Time sensitive", "Pricing review is scheduled for Friday."]].map(([title,tag,copy])=><div className="suggestion" key={title}><div className="suggestion-icon"><Lightbulb size={15}/></div><div style={{flex:1}}><strong>{title}</strong><p>{copy}</p></div><span className="tag">{tag}</span></div>)}</article>}
function Funnel(){ return <article className="card"><div className="chart-head"><div><h2 className="card-title">Pipeline funnel</h2><p className="card-subtitle">Account progression this quarter</p></div><ChevronRight size={17} color="#94a3b8"/></div><div className="funnel">{[["Targeted","100%","#dbeafe"],["Engaged","74%","#93c5fd"],["Qualified","51%","#60a5fa"],["In strategy","32%","#3b82f6"],["Proposal","18%","#2563eb"]].map(([name,width,color])=><div className="funnel-row" key={name}><span className="funnel-label">{name}</span><div className="funnel-bar" style={{width,background:color}}/><b className="funnel-value">{width}</b></div>)}</div></article> }
function ActivityFeed(){return <article className="card"><div className="chart-head"><div><h2 className="card-title">Recent activity</h2><p className="card-subtitle">Across your priority accounts</p></div><span className="period">View all</span></div>{[["Maya Chen", "reviewed the Novartis account strategy", "12 min ago"],["Research agent", "found 4 new signals for Airtel Business", "38 min ago"],["Jordan Lee", "opened your Lumen executive brief", "1 hr ago"],["Outreach agent", "generated a sequence for Atlassian", "2 hrs ago"]].map(([actor,action,time])=><div className="activity" key={time}><div className="dotline"/><div><p><strong>{actor}</strong> {action}</p><span className="activity-time">{time}</span></div></div>)}</article> }
function AccountsPreview(){return <article className="card accounts-preview"><div className="chart-head"><div><h2 className="card-title">Priority accounts</h2><p className="card-subtitle">Highest potential accounts requiring attention</p></div><span className="period">View accounts</span></div><div className="account-row" style={{color:"#94a3b8",fontSize:10,fontWeight:700,textTransform:"uppercase",letterSpacing:".5px"}}><span>Account</span><span>Pipeline</span><span>Stage</span><span>Intent score</span><span>Priority</span></div>{accounts.map(([name,industry,pipeline,stage,score])=><div className="account-row" key={name}><div className="account-name"><span className="company-icon">{name.slice(0,1)}</span><span>{name}<small style={{display:"block",color:"#64748b",fontWeight:400,marginTop:2}}>{industry}</small></span></div><span>{pipeline}</span><span>{stage}</span><span className="score">{score}/100</span><span className="pill">High</span></div>)}</article>}

export function Dashboard(){return <AppShell><div className="content"><div className="header-row"><div><div className="eyebrow">THURSDAY, AUGUST 1</div><h1 className="page-title">Good morning, John</h1><p className="subtle">Here&apos;s your account intelligence briefing for today.</p></div><button className="primary-button"><Plus size={16}/> Create account</button></div><MetricCards/><div className="dashboard-grid"><div className="stack"><RevenueChart/><AccountsPreview/></div><div className="stack"><Suggestions/><Funnel/><ActivityFeed/></div></div></div></AppShell>}
